name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-python:
    name: Deploy Python App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy Python App
        run: python app.py
